// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuikForm.Repositories.Contexts;

#nullable disable

namespace QuikForm.Repositories.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240131111924_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QuikForm.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("QuikForm.Entities.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Fields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Aut.",
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 2,
                            Label = "Distinctio.",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 3,
                            Label = "Magni.",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 4,
                            Label = "Id.",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 5,
                            Label = "Nobis.",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 6,
                            Label = "Et.",
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 7,
                            Label = "Commodi.",
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 8,
                            Label = "Aut.",
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 9,
                            Label = "Et.",
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 10,
                            Label = "Iste.",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 11,
                            Label = "Voluptatem.",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 12,
                            Label = "Qui.",
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 13,
                            Label = "Porro.",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 14,
                            Label = "Itaque.",
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 15,
                            Label = "Earum.",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 16,
                            Label = "Veniam.",
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 17,
                            Label = "Velit.",
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 18,
                            Label = "Dolor.",
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 19,
                            Label = "Qui.",
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 20,
                            Label = "Ut.",
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 21,
                            Label = "Nihil.",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 22,
                            Label = "Eum.",
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 23,
                            Label = "Blanditiis.",
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 24,
                            Label = "Ratione.",
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 25,
                            Label = "Eaque.",
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 26,
                            Label = "Eveniet.",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 27,
                            Label = "Sint.",
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 28,
                            Label = "Soluta.",
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 29,
                            Label = "Et.",
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 30,
                            Label = "Eveniet.",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 31,
                            Label = "Voluptatibus.",
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 32,
                            Label = "Incidunt.",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 33,
                            Label = "Officia.",
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 34,
                            Label = "Est.",
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 35,
                            Label = "Vitae.",
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 36,
                            Label = "Provident.",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 37,
                            Label = "Facere.",
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 38,
                            Label = "Et.",
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 39,
                            Label = "In.",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 40,
                            Label = "Debitis.",
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 41,
                            Label = "Vitae.",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 42,
                            Label = "At.",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 43,
                            Label = "Ut.",
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 44,
                            Label = "Sed.",
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 45,
                            Label = "Sit.",
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 46,
                            Label = "Esse.",
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 47,
                            Label = "Est.",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 48,
                            Label = "Ut.",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 49,
                            Label = "Quasi.",
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 50,
                            Label = "Nulla.",
                            QuestionId = 8
                        });
                });

            modelBuilder.Entity("QuikForm.Entities.FieldRecord", b =>
                {
                    b.Property<int?>("FieldId")
                        .HasColumnType("int");

                    b.Property<int?>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("CustomAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FieldId", "RecordId");

                    b.HasIndex("RecordId");

                    b.ToTable("FieldRecords");
                });

            modelBuilder.Entity("QuikForm.Entities.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Forms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 2, 1, 8, 35, 803, DateTimeKind.Unspecified).AddTicks(2559),
                            Description = "Incidunt sit corporis quod. In aliquid pariatur. In voluptas esse asperiores accusantium sit sunt velit est consectetur. Quia magnam pariatur.",
                            Title = "Voluptatem omnis magnam totam quis.",
                            UpdatedAt = new DateTime(2024, 1, 16, 22, 21, 51, 460, DateTimeKind.Unspecified).AddTicks(4619)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 16, 47, 4, 188, DateTimeKind.Unspecified).AddTicks(6931),
                            Description = "Maxime et qui ab qui. Laboriosam qui tempore sapiente itaque eius aut. Incidunt autem et dolorum autem nesciunt. Non omnis voluptas ut ex est atque. Minima consequatur aperiam quod enim nesciunt repellat in illum consequatur. Numquam voluptatem quia est asperiores hic.",
                            Title = "Ipsa nostrum ab eaque magni.",
                            UpdatedAt = new DateTime(2024, 1, 25, 4, 24, 54, 785, DateTimeKind.Unspecified).AddTicks(8983)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 19, 46, 20, 55, DateTimeKind.Unspecified).AddTicks(1316),
                            Description = "Nesciunt nostrum quaerat quasi hic molestiae magni. In et aut nam sed totam sunt qui. Qui asperiores doloremque cupiditate dolores explicabo aut a. Perspiciatis amet modi magni doloribus vitae molestiae nobis. Et omnis cupiditate sit ut blanditiis perspiciatis blanditiis. Earum vero tenetur eum veritatis quia autem beatae.",
                            Title = "Dignissimos quaerat mollitia et sed.",
                            UpdatedAt = new DateTime(2024, 1, 24, 21, 58, 28, 945, DateTimeKind.Unspecified).AddTicks(5036)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 4, 15, 14, 30, 545, DateTimeKind.Unspecified).AddTicks(1839),
                            Description = "Tempore ut voluptas molestias. Est quia repellat excepturi. Blanditiis perferendis sunt. Tenetur eum iste officia ipsa architecto.",
                            Title = "Cum odio quo qui consequuntur.",
                            UpdatedAt = new DateTime(2024, 1, 14, 21, 52, 13, 658, DateTimeKind.Unspecified).AddTicks(860)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 18, 39, 13, 297, DateTimeKind.Unspecified).AddTicks(2110),
                            Description = "Voluptatem sunt sint. Vero vero soluta vel ullam. Et id praesentium non sequi qui eos illum omnis.",
                            Title = "Distinctio nam illo qui reprehenderit.",
                            UpdatedAt = new DateTime(2024, 1, 28, 1, 7, 44, 57, DateTimeKind.Unspecified).AddTicks(8581)
                        });
                });

            modelBuilder.Entity("QuikForm.Entities.InputType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Markup")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("InputTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Champs texte",
                            Markup = "text"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Champs paragraphe",
                            Markup = "textarea"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Choix multiples",
                            Markup = "checkbox"
                        },
                        new
                        {
                            Id = 4,
                            Label = "Choix unique",
                            Markup = "radio"
                        });
                });

            modelBuilder.Entity("QuikForm.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FormId")
                        .HasColumnType("int");

                    b.Property<int?>("InputTypeId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("InputTypeId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FormId = 4,
                            InputTypeId = 3,
                            IsMandatory = false,
                            Label = "Quibusdam illo voluptate recusandae eligendi."
                        },
                        new
                        {
                            Id = 2,
                            FormId = 3,
                            InputTypeId = 1,
                            IsMandatory = false,
                            Label = "Aperiam eum ullam quis ipsa."
                        },
                        new
                        {
                            Id = 3,
                            FormId = 3,
                            InputTypeId = 3,
                            IsMandatory = false,
                            Label = "Voluptatum nihil provident veniam provident."
                        },
                        new
                        {
                            Id = 4,
                            FormId = 5,
                            InputTypeId = 1,
                            IsMandatory = true,
                            Label = "Molestiae dolores nulla et minima."
                        },
                        new
                        {
                            Id = 5,
                            FormId = 3,
                            InputTypeId = 2,
                            IsMandatory = true,
                            Label = "Sunt veritatis error delectus odio."
                        },
                        new
                        {
                            Id = 6,
                            FormId = 5,
                            InputTypeId = 2,
                            IsMandatory = false,
                            Label = "Ducimus adipisci ratione ipsam et."
                        },
                        new
                        {
                            Id = 7,
                            FormId = 5,
                            InputTypeId = 4,
                            IsMandatory = false,
                            Label = "Consequatur consequatur consequatur quia et."
                        },
                        new
                        {
                            Id = 8,
                            FormId = 1,
                            InputTypeId = 3,
                            IsMandatory = true,
                            Label = "Earum explicabo amet iusto mollitia."
                        },
                        new
                        {
                            Id = 9,
                            FormId = 2,
                            InputTypeId = 4,
                            IsMandatory = false,
                            Label = "Et quia et natus natus."
                        },
                        new
                        {
                            Id = 10,
                            FormId = 4,
                            InputTypeId = 1,
                            IsMandatory = false,
                            Label = "Illo perspiciatis est molestias omnis."
                        },
                        new
                        {
                            Id = 11,
                            FormId = 1,
                            InputTypeId = 1,
                            IsMandatory = true,
                            Label = "Consequatur et ipsa ad consequatur."
                        },
                        new
                        {
                            Id = 12,
                            FormId = 5,
                            InputTypeId = 1,
                            IsMandatory = false,
                            Label = "Repellat consequuntur ex sit necessitatibus."
                        },
                        new
                        {
                            Id = 13,
                            FormId = 5,
                            InputTypeId = 2,
                            IsMandatory = false,
                            Label = "Soluta odit omnis ratione ut."
                        },
                        new
                        {
                            Id = 14,
                            FormId = 5,
                            InputTypeId = 3,
                            IsMandatory = false,
                            Label = "Corporis at voluptatibus rem beatae."
                        },
                        new
                        {
                            Id = 15,
                            FormId = 5,
                            InputTypeId = 4,
                            IsMandatory = false,
                            Label = "Debitis minus non voluptatem rerum."
                        },
                        new
                        {
                            Id = 16,
                            FormId = 1,
                            InputTypeId = 4,
                            IsMandatory = false,
                            Label = "Sed temporibus quis magni architecto."
                        },
                        new
                        {
                            Id = 17,
                            FormId = 3,
                            InputTypeId = 4,
                            IsMandatory = true,
                            Label = "Laudantium rem consequuntur quibusdam ut."
                        },
                        new
                        {
                            Id = 18,
                            FormId = 1,
                            InputTypeId = 4,
                            IsMandatory = true,
                            Label = "Quae et ut quia dolorum."
                        },
                        new
                        {
                            Id = 19,
                            FormId = 1,
                            InputTypeId = 1,
                            IsMandatory = false,
                            Label = "Dolorem voluptatem quo eum et."
                        },
                        new
                        {
                            Id = 20,
                            FormId = 5,
                            InputTypeId = 3,
                            IsMandatory = false,
                            Label = "Occaecati quos sit necessitatibus voluptates."
                        });
                });

            modelBuilder.Entity("QuikForm.Entities.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("QuikForm.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("QuikForm.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuikForm.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("QuikForm.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuikForm.Entities.Field", b =>
                {
                    b.HasOne("QuikForm.Entities.Question", "Question")
                        .WithMany("Fields")
                        .HasForeignKey("QuestionId");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuikForm.Entities.FieldRecord", b =>
                {
                    b.HasOne("QuikForm.Entities.Field", "Field")
                        .WithMany("FieldRecords")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuikForm.Entities.Record", "Record")
                        .WithMany("FieldRecords")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("QuikForm.Entities.Form", b =>
                {
                    b.HasOne("QuikForm.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("Forms")
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("QuikForm.Entities.Question", b =>
                {
                    b.HasOne("QuikForm.Entities.Form", "Form")
                        .WithMany("Questions")
                        .HasForeignKey("FormId");

                    b.HasOne("QuikForm.Entities.InputType", "InputType")
                        .WithMany("Questions")
                        .HasForeignKey("InputTypeId");

                    b.Navigation("Form");

                    b.Navigation("InputType");
                });

            modelBuilder.Entity("QuikForm.Entities.Record", b =>
                {
                    b.HasOne("QuikForm.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("QuikForm.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Forms");
                });

            modelBuilder.Entity("QuikForm.Entities.Field", b =>
                {
                    b.Navigation("FieldRecords");
                });

            modelBuilder.Entity("QuikForm.Entities.Form", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QuikForm.Entities.InputType", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QuikForm.Entities.Question", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("QuikForm.Entities.Record", b =>
                {
                    b.Navigation("FieldRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
