// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuikForm.Repositories.Contexts;

#nullable disable

namespace QuikForm.Repositories.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QuikForm.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("QuikForm.Entities.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Fields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Doloribus.",
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 2,
                            Label = "Culpa.",
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 3,
                            Label = "Illo.",
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 4,
                            Label = "Ea.",
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 5,
                            Label = "Et.",
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 6,
                            Label = "Incidunt.",
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 7,
                            Label = "Et.",
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 8,
                            Label = "Voluptates.",
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 9,
                            Label = "Sint.",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 10,
                            Label = "Maiores.",
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 11,
                            Label = "Commodi.",
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 12,
                            Label = "Fugiat.",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 13,
                            Label = "Voluptatem.",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 14,
                            Label = "Sit.",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 15,
                            Label = "Ipsum.",
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 16,
                            Label = "Et.",
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 17,
                            Label = "Temporibus.",
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 18,
                            Label = "Quis.",
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 19,
                            Label = "Asperiores.",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 20,
                            Label = "Exercitationem.",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 21,
                            Label = "Deserunt.",
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 22,
                            Label = "Et.",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 23,
                            Label = "Qui.",
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 24,
                            Label = "Soluta.",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 25,
                            Label = "Aspernatur.",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 26,
                            Label = "Quia.",
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 27,
                            Label = "Recusandae.",
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 28,
                            Label = "Veritatis.",
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 29,
                            Label = "Commodi.",
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 30,
                            Label = "Perferendis.",
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 31,
                            Label = "Dolore.",
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 32,
                            Label = "Facere.",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 33,
                            Label = "Voluptatem.",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 34,
                            Label = "Voluptas.",
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 35,
                            Label = "Necessitatibus.",
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 36,
                            Label = "Accusantium.",
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 37,
                            Label = "Labore.",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 38,
                            Label = "Optio.",
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 39,
                            Label = "Non.",
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 40,
                            Label = "Et.",
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 41,
                            Label = "Hic.",
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 42,
                            Label = "Iste.",
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 43,
                            Label = "Dolorem.",
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 44,
                            Label = "Sed.",
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 45,
                            Label = "Voluptatum.",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 46,
                            Label = "Consequuntur.",
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 47,
                            Label = "Aut.",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 48,
                            Label = "Et.",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 49,
                            Label = "Expedita.",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 50,
                            Label = "Libero.",
                            QuestionId = 10
                        });
                });

            modelBuilder.Entity("QuikForm.Entities.FieldRecord", b =>
                {
                    b.Property<int?>("FieldId")
                        .HasColumnType("int");

                    b.Property<int?>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("CustomAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FieldId", "RecordId");

                    b.HasIndex("RecordId");

                    b.ToTable("FieldRecords");
                });

            modelBuilder.Entity("QuikForm.Entities.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Forms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 4, 19, 51, 53, 793, DateTimeKind.Unspecified).AddTicks(606),
                            Description = "Dolore id molestias atque et dolorem. Facilis corrupti magni beatae eos voluptatem dignissimos consequatur. Officiis tenetur et eveniet et. Vel blanditiis quibusdam ea.",
                            Title = "Commodi voluptate dignissimos animi nobis.",
                            UpdatedAt = new DateTime(2024, 1, 28, 9, 39, 20, 328, DateTimeKind.Unspecified).AddTicks(4753)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 4, 14, 10, 23, 262, DateTimeKind.Unspecified).AddTicks(8380),
                            Description = "Rerum asperiores ut laudantium quod. Modi repudiandae architecto qui doloremque dolores laborum. Et est qui expedita et. Necessitatibus illum omnis autem repellendus totam quibusdam sed. Nihil eum sapiente eos facilis consectetur modi delectus.",
                            Title = "Ea sapiente aut illo culpa.",
                            UpdatedAt = new DateTime(2024, 1, 28, 17, 0, 42, 387, DateTimeKind.Unspecified).AddTicks(2628)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 14, 36, 7, 945, DateTimeKind.Unspecified).AddTicks(9315),
                            Description = "Quis inventore fugiat alias atque non. Qui tempora tempora hic iure quia. Amet modi rerum dolorum quis.",
                            Title = "Aliquid et ipsam nulla quam.",
                            UpdatedAt = new DateTime(2024, 1, 25, 8, 38, 59, 792, DateTimeKind.Unspecified).AddTicks(46)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 2, 4, 56, 14, 922, DateTimeKind.Unspecified).AddTicks(9470),
                            Description = "Magnam neque quasi architecto asperiores est. Et placeat aut sed aut dolor doloribus aut exercitationem. Eos explicabo animi amet earum amet. Aut eum rerum. Nobis consequatur quas aspernatur nostrum omnis ullam sunt quibusdam. Occaecati doloribus sunt dignissimos.",
                            Title = "Alias consequatur assumenda reiciendis nisi.",
                            UpdatedAt = new DateTime(2024, 1, 25, 15, 10, 39, 557, DateTimeKind.Unspecified).AddTicks(4555)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 17, 15, 0, 930, DateTimeKind.Unspecified).AddTicks(6311),
                            Description = "Praesentium id ut consequatur ut non labore voluptas. Nam omnis repellendus omnis officiis asperiores sit non. Quae eos reprehenderit fugiat reiciendis amet molestiae in quasi.",
                            Title = "Quis iste dolor dolor voluptatem.",
                            UpdatedAt = new DateTime(2024, 1, 14, 7, 25, 16, 57, DateTimeKind.Unspecified).AddTicks(6740)
                        });
                });

            modelBuilder.Entity("QuikForm.Entities.InputType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("InputTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Text"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Textarea"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Checkbox"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Radio"
                        });
                });

            modelBuilder.Entity("QuikForm.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FormId")
                        .HasColumnType("int");

                    b.Property<int?>("InputTypeId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("InputTypeId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FormId = 5,
                            InputTypeId = 4,
                            IsMandatory = false,
                            Label = "Reprehenderit sit rem consectetur vel."
                        },
                        new
                        {
                            Id = 2,
                            FormId = 1,
                            InputTypeId = 1,
                            IsMandatory = true,
                            Label = "Nihil quae autem quisquam minus."
                        },
                        new
                        {
                            Id = 3,
                            FormId = 3,
                            InputTypeId = 4,
                            IsMandatory = true,
                            Label = "Enim tenetur quasi occaecati quam."
                        },
                        new
                        {
                            Id = 4,
                            FormId = 2,
                            InputTypeId = 4,
                            IsMandatory = true,
                            Label = "Facere odio autem iusto quis."
                        },
                        new
                        {
                            Id = 5,
                            FormId = 4,
                            InputTypeId = 2,
                            IsMandatory = true,
                            Label = "Amet illo perspiciatis aliquid mollitia."
                        },
                        new
                        {
                            Id = 6,
                            FormId = 3,
                            InputTypeId = 2,
                            IsMandatory = true,
                            Label = "Voluptatem dolore repellendus iure ad."
                        },
                        new
                        {
                            Id = 7,
                            FormId = 4,
                            InputTypeId = 2,
                            IsMandatory = true,
                            Label = "Cumque tempore maxime sit officia."
                        },
                        new
                        {
                            Id = 8,
                            FormId = 1,
                            InputTypeId = 1,
                            IsMandatory = true,
                            Label = "Dolorum enim cupiditate ut consequatur."
                        },
                        new
                        {
                            Id = 9,
                            FormId = 3,
                            InputTypeId = 1,
                            IsMandatory = false,
                            Label = "Sint iste voluptatem veritatis esse."
                        },
                        new
                        {
                            Id = 10,
                            FormId = 5,
                            InputTypeId = 3,
                            IsMandatory = false,
                            Label = "Quis ab aut assumenda perspiciatis."
                        },
                        new
                        {
                            Id = 11,
                            FormId = 4,
                            InputTypeId = 3,
                            IsMandatory = false,
                            Label = "Quis dolore aspernatur provident voluptatem."
                        },
                        new
                        {
                            Id = 12,
                            FormId = 1,
                            InputTypeId = 1,
                            IsMandatory = false,
                            Label = "Aut nihil quasi earum id."
                        },
                        new
                        {
                            Id = 13,
                            FormId = 2,
                            InputTypeId = 1,
                            IsMandatory = false,
                            Label = "Consequuntur laudantium temporibus suscipit inventore."
                        },
                        new
                        {
                            Id = 14,
                            FormId = 5,
                            InputTypeId = 1,
                            IsMandatory = false,
                            Label = "Nihil in libero quae consectetur."
                        },
                        new
                        {
                            Id = 15,
                            FormId = 5,
                            InputTypeId = 4,
                            IsMandatory = false,
                            Label = "Inventore qui veritatis id quo."
                        },
                        new
                        {
                            Id = 16,
                            FormId = 2,
                            InputTypeId = 2,
                            IsMandatory = true,
                            Label = "Quia cumque at eos occaecati."
                        },
                        new
                        {
                            Id = 17,
                            FormId = 1,
                            InputTypeId = 2,
                            IsMandatory = true,
                            Label = "Voluptate quisquam asperiores illo accusamus."
                        },
                        new
                        {
                            Id = 18,
                            FormId = 2,
                            InputTypeId = 3,
                            IsMandatory = false,
                            Label = "Perferendis qui vel pariatur sint."
                        },
                        new
                        {
                            Id = 19,
                            FormId = 5,
                            InputTypeId = 4,
                            IsMandatory = false,
                            Label = "Reprehenderit saepe velit deleniti at."
                        },
                        new
                        {
                            Id = 20,
                            FormId = 1,
                            InputTypeId = 3,
                            IsMandatory = true,
                            Label = "Fugit labore aut facilis error."
                        });
                });

            modelBuilder.Entity("QuikForm.Entities.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("QuikForm.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("QuikForm.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuikForm.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("QuikForm.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuikForm.Entities.Field", b =>
                {
                    b.HasOne("QuikForm.Entities.Question", "Question")
                        .WithMany("Fields")
                        .HasForeignKey("QuestionId");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuikForm.Entities.FieldRecord", b =>
                {
                    b.HasOne("QuikForm.Entities.Field", "Field")
                        .WithMany("FieldRecords")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuikForm.Entities.Record", "Record")
                        .WithMany("FieldRecords")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("QuikForm.Entities.Form", b =>
                {
                    b.HasOne("QuikForm.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("Forms")
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("QuikForm.Entities.Question", b =>
                {
                    b.HasOne("QuikForm.Entities.Form", "Form")
                        .WithMany("Questions")
                        .HasForeignKey("FormId");

                    b.HasOne("QuikForm.Entities.InputType", "InputType")
                        .WithMany("Questions")
                        .HasForeignKey("InputTypeId");

                    b.Navigation("Form");

                    b.Navigation("InputType");
                });

            modelBuilder.Entity("QuikForm.Entities.Record", b =>
                {
                    b.HasOne("QuikForm.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("QuikForm.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Forms");
                });

            modelBuilder.Entity("QuikForm.Entities.Field", b =>
                {
                    b.Navigation("FieldRecords");
                });

            modelBuilder.Entity("QuikForm.Entities.Form", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QuikForm.Entities.InputType", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QuikForm.Entities.Question", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("QuikForm.Entities.Record", b =>
                {
                    b.Navigation("FieldRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
