// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuikForm.Repositories.Contexts;

#nullable disable

namespace QuikForm.Repositories.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QuikForm.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("QuikForm.Entities.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Fields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Porro.",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 2,
                            Label = "Pariatur.",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 3,
                            Label = "Eveniet.",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 4,
                            Label = "Magni.",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 5,
                            Label = "Ea.",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 6,
                            Label = "Molestiae.",
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 7,
                            Label = "Unde.",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 8,
                            Label = "Sed.",
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 9,
                            Label = "Voluptatem.",
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 10,
                            Label = "Consequatur.",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 11,
                            Label = "Repellendus.",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 12,
                            Label = "Aliquid.",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 13,
                            Label = "Quia.",
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 14,
                            Label = "Veritatis.",
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 15,
                            Label = "Eligendi.",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 16,
                            Label = "Odio.",
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 17,
                            Label = "Odio.",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 18,
                            Label = "Quia.",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 19,
                            Label = "Omnis.",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 20,
                            Label = "Mollitia.",
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 21,
                            Label = "Quis.",
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 22,
                            Label = "Aliquid.",
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 23,
                            Label = "Odio.",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 24,
                            Label = "Ipsum.",
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 25,
                            Label = "Delectus.",
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 26,
                            Label = "Enim.",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 27,
                            Label = "Dicta.",
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 28,
                            Label = "Nesciunt.",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 29,
                            Label = "Inventore.",
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 30,
                            Label = "Ipsum.",
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 31,
                            Label = "Aut.",
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 32,
                            Label = "Ullam.",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 33,
                            Label = "Deserunt.",
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 34,
                            Label = "Rerum.",
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 35,
                            Label = "Blanditiis.",
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 36,
                            Label = "Dolor.",
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 37,
                            Label = "Reprehenderit.",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 38,
                            Label = "Qui.",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 39,
                            Label = "Nobis.",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 40,
                            Label = "Vel.",
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 41,
                            Label = "Sed.",
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 42,
                            Label = "Occaecati.",
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 43,
                            Label = "Eos.",
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 44,
                            Label = "Iusto.",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 45,
                            Label = "Eum.",
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 46,
                            Label = "Pariatur.",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 47,
                            Label = "Maxime.",
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 48,
                            Label = "Saepe.",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 49,
                            Label = "Necessitatibus.",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 50,
                            Label = "Molestiae.",
                            QuestionId = 10
                        });
                });

            modelBuilder.Entity("QuikForm.Entities.FieldRecord", b =>
                {
                    b.Property<int?>("FieldId")
                        .HasColumnType("int");

                    b.Property<int?>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("CustomAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FieldId", "RecordId");

                    b.HasIndex("RecordId");

                    b.ToTable("FieldRecords");
                });

            modelBuilder.Entity("QuikForm.Entities.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Forms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 2, 17, 57, 25, 551, DateTimeKind.Unspecified).AddTicks(8931),
                            Description = "Adipisci omnis voluptatem cum. Cum nobis cupiditate ad. Vel autem dolorem quisquam at nostrum quis velit architecto rerum. Hic nihil qui id numquam voluptatem laudantium. Similique recusandae dicta et ea impedit. Sequi rerum assumenda ut.",
                            Title = "Magnam neque vel culpa sit.",
                            UpdatedAt = new DateTime(2024, 1, 20, 10, 56, 39, 780, DateTimeKind.Unspecified).AddTicks(3367)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 3, 14, 1, 12, 331, DateTimeKind.Unspecified).AddTicks(782),
                            Description = "Possimus voluptatem voluptates ut et unde. Consequatur omnis aperiam facere maxime odio sit modi. Deserunt eius ut.",
                            Title = "Vitae voluptatum praesentium nobis pariatur.",
                            UpdatedAt = new DateTime(2024, 1, 22, 17, 0, 8, 183, DateTimeKind.Unspecified).AddTicks(4787)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 4, 36, 50, 21, DateTimeKind.Unspecified).AddTicks(2400),
                            Description = "Id debitis suscipit amet quae distinctio. Voluptatem non enim. Quo inventore vitae et commodi fugiat. Numquam ut fugit voluptates sit explicabo ut et. Necessitatibus aut vitae et. Nobis consectetur possimus ipsa quis.",
                            Title = "Incidunt molestias ad quibusdam dolorem.",
                            UpdatedAt = new DateTime(2024, 1, 15, 1, 41, 14, 665, DateTimeKind.Unspecified).AddTicks(6154)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 4, 23, 29, 43, 566, DateTimeKind.Unspecified).AddTicks(9323),
                            Description = "Perferendis voluptas doloribus est aliquid quia nemo dolorem asperiores laudantium. Atque repellendus aut voluptatibus atque iste deserunt sit. Eos in nobis et illum aut. Omnis molestiae officia quis repellat iste id quia dolor. Et doloribus ut deleniti dolores animi. Quidem rem non quis voluptatibus velit quia.",
                            Title = "Error eos aut non laudantium.",
                            UpdatedAt = new DateTime(2024, 1, 30, 3, 13, 36, 172, DateTimeKind.Unspecified).AddTicks(1101)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 2, 19, 28, 6, 21, DateTimeKind.Unspecified).AddTicks(396),
                            Description = "Harum esse sit libero quam harum sint. Quas qui beatae similique. Nemo tempore aliquid ea optio. A corporis sit. Eum molestiae beatae ut.",
                            Title = "Repellendus dolorum ratione fugiat in.",
                            UpdatedAt = new DateTime(2024, 1, 10, 10, 21, 55, 937, DateTimeKind.Unspecified).AddTicks(4491)
                        });
                });

            modelBuilder.Entity("QuikForm.Entities.InputType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("InputTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "text"
                        },
                        new
                        {
                            Id = 2,
                            Name = "textarea"
                        },
                        new
                        {
                            Id = 3,
                            Name = "checkbox"
                        },
                        new
                        {
                            Id = 4,
                            Name = "radio"
                        });
                });

            modelBuilder.Entity("QuikForm.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FormId")
                        .HasColumnType("int");

                    b.Property<int?>("InputTypeId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("InputTypeId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FormId = 1,
                            InputTypeId = 3,
                            IsMandatory = false,
                            Label = "Laboriosam officiis quisquam modi voluptatem."
                        },
                        new
                        {
                            Id = 2,
                            FormId = 2,
                            InputTypeId = 3,
                            IsMandatory = true,
                            Label = "Consequuntur sint aspernatur tenetur doloribus."
                        },
                        new
                        {
                            Id = 3,
                            FormId = 4,
                            InputTypeId = 2,
                            IsMandatory = true,
                            Label = "Perferendis numquam fugiat quidem illum."
                        },
                        new
                        {
                            Id = 4,
                            FormId = 2,
                            InputTypeId = 4,
                            IsMandatory = true,
                            Label = "Officia odit in et fugiat."
                        },
                        new
                        {
                            Id = 5,
                            FormId = 3,
                            InputTypeId = 2,
                            IsMandatory = false,
                            Label = "Animi veniam earum exercitationem modi."
                        },
                        new
                        {
                            Id = 6,
                            FormId = 3,
                            InputTypeId = 3,
                            IsMandatory = true,
                            Label = "Soluta sit et distinctio consectetur."
                        },
                        new
                        {
                            Id = 7,
                            FormId = 2,
                            InputTypeId = 3,
                            IsMandatory = true,
                            Label = "Vitae totam at accusantium labore."
                        },
                        new
                        {
                            Id = 8,
                            FormId = 5,
                            InputTypeId = 1,
                            IsMandatory = true,
                            Label = "Aliquid fuga omnis perspiciatis eligendi."
                        },
                        new
                        {
                            Id = 9,
                            FormId = 2,
                            InputTypeId = 1,
                            IsMandatory = true,
                            Label = "Quia odio aspernatur illo occaecati."
                        },
                        new
                        {
                            Id = 10,
                            FormId = 5,
                            InputTypeId = 2,
                            IsMandatory = false,
                            Label = "Voluptate rerum laudantium ipsum impedit."
                        },
                        new
                        {
                            Id = 11,
                            FormId = 3,
                            InputTypeId = 2,
                            IsMandatory = true,
                            Label = "Quos iste omnis omnis labore."
                        },
                        new
                        {
                            Id = 12,
                            FormId = 1,
                            InputTypeId = 3,
                            IsMandatory = false,
                            Label = "Quo omnis quibusdam illo corporis."
                        },
                        new
                        {
                            Id = 13,
                            FormId = 1,
                            InputTypeId = 3,
                            IsMandatory = true,
                            Label = "Ut vel architecto deserunt eum."
                        },
                        new
                        {
                            Id = 14,
                            FormId = 3,
                            InputTypeId = 1,
                            IsMandatory = true,
                            Label = "Laboriosam laudantium magnam cumque voluptas."
                        },
                        new
                        {
                            Id = 15,
                            FormId = 3,
                            InputTypeId = 4,
                            IsMandatory = false,
                            Label = "Et tempora similique aut perspiciatis."
                        },
                        new
                        {
                            Id = 16,
                            FormId = 4,
                            InputTypeId = 2,
                            IsMandatory = true,
                            Label = "Suscipit voluptas eveniet cupiditate quasi."
                        },
                        new
                        {
                            Id = 17,
                            FormId = 4,
                            InputTypeId = 3,
                            IsMandatory = false,
                            Label = "Alias vel qui et aut."
                        },
                        new
                        {
                            Id = 18,
                            FormId = 2,
                            InputTypeId = 4,
                            IsMandatory = true,
                            Label = "Ea eveniet cupiditate explicabo praesentium."
                        },
                        new
                        {
                            Id = 19,
                            FormId = 2,
                            InputTypeId = 3,
                            IsMandatory = false,
                            Label = "Dolores quia provident fuga minima."
                        },
                        new
                        {
                            Id = 20,
                            FormId = 4,
                            InputTypeId = 2,
                            IsMandatory = true,
                            Label = "Voluptatem consequatur voluptate rem voluptatem."
                        });
                });

            modelBuilder.Entity("QuikForm.Entities.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("QuikForm.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("QuikForm.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuikForm.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("QuikForm.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuikForm.Entities.Field", b =>
                {
                    b.HasOne("QuikForm.Entities.Question", "Question")
                        .WithMany("Fields")
                        .HasForeignKey("QuestionId");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuikForm.Entities.FieldRecord", b =>
                {
                    b.HasOne("QuikForm.Entities.Field", "Field")
                        .WithMany("FieldRecords")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuikForm.Entities.Record", "Record")
                        .WithMany("FieldRecords")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("QuikForm.Entities.Form", b =>
                {
                    b.HasOne("QuikForm.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("Forms")
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("QuikForm.Entities.Question", b =>
                {
                    b.HasOne("QuikForm.Entities.Form", "Form")
                        .WithMany("Questions")
                        .HasForeignKey("FormId");

                    b.HasOne("QuikForm.Entities.InputType", "InputType")
                        .WithMany("Questions")
                        .HasForeignKey("InputTypeId");

                    b.Navigation("Form");

                    b.Navigation("InputType");
                });

            modelBuilder.Entity("QuikForm.Entities.Record", b =>
                {
                    b.HasOne("QuikForm.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("QuikForm.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Forms");
                });

            modelBuilder.Entity("QuikForm.Entities.Field", b =>
                {
                    b.Navigation("FieldRecords");
                });

            modelBuilder.Entity("QuikForm.Entities.Form", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QuikForm.Entities.InputType", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QuikForm.Entities.Question", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("QuikForm.Entities.Record", b =>
                {
                    b.Navigation("FieldRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
